/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.AdExchange;
import Business.Bank;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.AdExAdminRole;
import Business.Role.AdminRole;
import Business.Role.SysAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnanthaShankar
 */
public class ManageAdExchangeAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdExchangeAccountJPanel
     */
    private JPanel upc;
    private EcoSystem system;
    private ManageAdExChangeJPanel sa;
    private AdExchange ae;
    public ManageAdExchangeAccountJPanel(JPanel upc, EcoSystem system, AdExchange ae, ManageAdExChangeJPanel sa) {
        initComponents();
        this.upc = upc;
        this.system = system;
        this.sa = sa;
        this.ae = ae;
        populateTable();
        populateAdComboBx();
    }

    public void populateAdComboBx() {
        adExJCmbBx.removeAllItems();
        
            adExJCmbBx.addItem(ae);
        
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) usrAcctJTbl.getModel();
        dtm.setRowCount(0);

       // AdExchange ae = (AdExchange) adExJCmbBx.getSelectedItem();
        for (UserAccount ua : ae.getUserAccountDirectory().getUserAccountList()) {
            Object row[] = new Object[2];
            row[0] = ua;
            row[1] = ae;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usrAcctJTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        usrNmJTxtField = new javax.swing.JTextField();
        passwordJTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nmJTxtField = new javax.swing.JTextField();
        createJBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adExJCmbBx = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        usrAcctJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "AdExchange Name"
            }
        ));
        jScrollPane1.setViewportView(usrAcctJTbl);

        jLabel1.setText("UserName");

        usrNmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrNmJTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        nmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmJTxtFieldActionPerformed(evt);
            }
        });

        createJBtn.setText("Create");
        createJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        jLabel3.setText("AdExChange");

        adExJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        adExJCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adExJCmbBxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createJBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adExJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adExJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(createJBtn)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmJTxtFieldActionPerformed

    private void createJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJBtnActionPerformed
        // TODO add your handling code here:

        if (usrNmJTxtField.getText().trim().length() > 0 && passwordJTxtField.getText().trim().length() > 0
                && nmJTxtField.getText().trim().length() > 0) {

            String userName = usrNmJTxtField.getText().trim();
            Enterprise inEnterprise = null;
            Organization inOrganization = null;
            UserAccount userAccount = system.getUserAccountDirectory().searchUser(userName);
            if (userAccount == null) {
                    for (Network n : system.getNetworkList()) {
                        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                            userAccount = e.getUserAccountDirectory().searchUser(userName);
                            if (userAccount == null) {
                                for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                                    userAccount = o.getUserAccountDirectory().searchUser(userName);
                                    if (userAccount != null) {
                                        inOrganization = o;
                                        inEnterprise = e;

                                        break;
                                    }

                                }
                            } else {
                                inEnterprise = e;
                                break;
                            }
                            if (inOrganization != null) {
                                break;
                            }
                        }
                        if (inEnterprise != null) {
                            break;
                        }
                    }

                }

            if (userAccount == null) {
            for (Bank b : system.getBankDirectory().getBankList()) {
                userAccount = b.getUserAccountDirectory().searchUser(userName);
                if (userAccount == null) {
                    for (Organization o : b.getOrganizationDirectory().getOrgList()) {
                        userAccount = o.getUserAccountDirectory().searchUser(userName);
                        if (userAccount != null) {
                            break;
                        }
                    }
                } else {
                    break;
                }
            } 
        }

            if (userAccount == null) {
                for (AdExchange ae : system.getAdExDir().getAdExchangeList()) {
                    userAccount = ae.getUserAccountDirectory().searchUser(userName);
                    if (userAccount == null) {
                        for (Organization o : ae.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().searchUser(userName);
                            if (userAccount != null) {
                                break;
                            }
                        }
                    } else {
                        break;
                    }
                } 
            }
            if(userAccount == null){
                AdExchange ae = (AdExchange) adExJCmbBx.getSelectedItem();
                Person p = ae.getPersonDirectory().createPerson(nmJTxtField.getText().trim());
                ae.getUserAccountDirectory().createUserAccount(userName, passwordJTxtField.getText().trim(), p, new AdExAdminRole());
                populateTable();
                JOptionPane.showMessageDialog(null, "User Account Successfully Created");
                upc.remove(this);
                CardLayout layout = (CardLayout) upc.getLayout();
                layout.previous(upc);
            }
            else {
                    JOptionPane.showMessageDialog(null, "Username already exists. Please use different Username");
                }
        } else {
            JOptionPane.showMessageDialog(null, "Please Enter Values for Username or Password or Name");
        }
    }//GEN-LAST:event_createJBtnActionPerformed

    private void usrNmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrNmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrNmJTxtFieldActionPerformed

    private void adExJCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adExJCmbBxActionPerformed
        // TODO add your handling code here:
        populateAdComboBx();
    }//GEN-LAST:event_adExJCmbBxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adExJCmbBx;
    private javax.swing.JButton createJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmJTxtField;
    private javax.swing.JTextField passwordJTxtField;
    private javax.swing.JTable usrAcctJTbl;
    private javax.swing.JTextField usrNmJTxtField;
    // End of variables declaration//GEN-END:variables
}
