/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.AdExchange;
import Business.Bank;
import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.AdminRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnanthaShankar
 */
public class ManageEnterpriseUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseUserAccountJPanel
     */
    private JPanel upc;
    private EcoSystem system;
    private SysAdminWorkAreaJPanel sa;

    public ManageEnterpriseUserAccountJPanel(JPanel upc, EcoSystem system, SysAdminWorkAreaJPanel sa) {
        initComponents();
        this.upc = upc;
        this.system = system;
        this.sa = sa;
        populateTable();
        networkCombo();
        populateEnterpriseComboBx();

    }

    public void populateTable() {
        ((DefaultTableModel) usrAcctJTbl.getModel()).setRowCount(0);
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount ua : e.getUserAccountDirectory().getUserAccountList()) {
                    addRow(ua, e, n);
                }
                for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                    for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                        addRow(ua, e, n);
                    }
                }
            }
        }
    }

    protected void networkCombo() {
        networkJCmbBx.removeAllItems();
        for (Network n : system.getNetworkList()) {
            networkJCmbBx.addItem(n);
        }
    }

    public void addRow(UserAccount ua, Enterprise e, Network n) {
        DefaultTableModel dtm = (DefaultTableModel) usrAcctJTbl.getModel();

        Object row[] = new Object[4];
        row[0] = ua;
        row[1] = e.getType();
        row[2] = e;
        row[3] = n;
        dtm.addRow(row);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usrAcctJTbl = new javax.swing.JTable();
        usrNmJTxtField = new javax.swing.JTextField();
        passwordJTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkJCmbBx = new javax.swing.JComboBox();
        entJCmbBx = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createJBtn = new javax.swing.JButton();
        nmJTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        usrAcctJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Enterprise Type", "Enterprise", "Network"
            }
        ));
        jScrollPane1.setViewportView(usrAcctJTbl);

        jLabel1.setText("UserName");

        jLabel2.setText("Password");

        networkJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJCmbBxActionPerformed(evt);
            }
        });

        entJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        entJCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entJCmbBxActionPerformed(evt);
            }
        });

        jLabel3.setText("Network");

        jLabel4.setText("Enterprise");

        createJBtn.setText("Create");
        createJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJBtnActionPerformed(evt);
            }
        });

        nmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmJTxtFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(networkJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(entJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(66, 66, 66)
                        .addComponent(createJBtn)))
                .addGap(96, 172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(createJBtn))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void populateEnterpriseComboBx() {
        entJCmbBx.removeAllItems();
        if (networkJCmbBx.getItemCount() > 0) {
            Network n = (Network) networkJCmbBx.getItemAt(0);
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                entJCmbBx.addItem(e);
            }
        }
    }

    protected void populateEnterpriseComboBx(Network n) {
        entJCmbBx.removeAllItems();
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            entJCmbBx.addItem(e);
        }
    }

    private void networkJCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJCmbBxActionPerformed
        Network n = (Network) networkJCmbBx.getSelectedItem();
        if (n != null) {
            populateEnterpriseComboBx(n);
        }
    }//GEN-LAST:event_networkJCmbBxActionPerformed


    private void entJCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entJCmbBxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_entJCmbBxActionPerformed

    private void createJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJBtnActionPerformed
        // TODO add your handling code here:
        if(networkJCmbBx.getItemCount() > 0 && entJCmbBx.getItemCount() > 0){
        Enterprise en = (Enterprise) entJCmbBx.getSelectedItem();
        if (usrNmJTxtField.getText().trim().length() > 0 && passwordJTxtField.getText().trim().length() > 0
                && nmJTxtField.getText().trim().length() > 0) {

            String userName = usrNmJTxtField.getText().trim();
            Enterprise inEnterprise = null;
            Organization inOrganization = null;
            UserAccount userAccount = system.getUserAccountDirectory().searchUser(userName);
            if (userAccount == null) {
                    for (Network n : system.getNetworkList()) {
                        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                            userAccount = e.getUserAccountDirectory().searchUser(userName);
                            if (userAccount == null) {
                                for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                                    userAccount = o.getUserAccountDirectory().searchUser(userName);
                                    if (userAccount != null) {
                                        inOrganization = o;
                                        inEnterprise = e;

                                        break;
                                    }

                                }
                            } else {
                                inEnterprise = e;
                                break;
                            }
                            if (inOrganization != null) {
                                break;
                            }
                        }
                        if (inEnterprise != null) {
                            break;
                        }
                    }

                }

            if (userAccount == null) {
            for (Bank b : system.getBankDirectory().getBankList()) {
                userAccount = b.getUserAccountDirectory().searchUser(userName);
                if (userAccount == null) {
                    for (Organization o : b.getOrganizationDirectory().getOrgList()) {
                        userAccount = o.getUserAccountDirectory().searchUser(userName);
                        if (userAccount != null) {
                            break;
                        }
                    }
                } else {
                    break;
                }
            } 
        }

            if (userAccount == null) {
                for (AdExchange ae : system.getAdExDir().getAdExchangeList()) {
                    userAccount = ae.getUserAccountDirectory().searchUser(userName);
                    if (userAccount == null) {
                        for (Organization o : ae.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().searchUser(userName);
                            if (userAccount != null) {
                                break;
                            }
                        }
                    } else {
                        break;
                    }
                } 
            }

            if (userAccount == null) {
                Person p = en.getPersonDirectory().createPerson(nmJTxtField.getText().trim());
                en.getUserAccountDirectory().createUserAccount(usrNmJTxtField.getText().trim(), passwordJTxtField.getText().trim(), p, new AdminRole());
                JOptionPane.showMessageDialog(null, "User Account Successfully Created");
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "Username already exists. Please use different Username");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Enter Values for Username or Password or Name");
        }
       } else {
            JOptionPane.showMessageDialog(null, "Invalid Creation");
        }
    }//GEN-LAST:event_createJBtnActionPerformed

    private void nmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmJTxtFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        sa.populateNetworkTree();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJBtn;
    private javax.swing.JComboBox entJCmbBx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkJCmbBx;
    private javax.swing.JTextField nmJTxtField;
    private javax.swing.JTextField passwordJTxtField;
    private javax.swing.JTable usrAcctJTbl;
    private javax.swing.JTextField usrNmJTxtField;
    // End of variables declaration//GEN-END:variables
}
