/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.AdExchange;
import Business.Bank;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.Role.AdminRole;
import Business.Role.BankAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnanthaShankar
 */
public class ManageBanksAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageBanksAccountJPanel
     */
    private JPanel upc;
    private EcoSystem system;
    private ManageBankDirectoryJPanel sa;
    private Bank bank;

    public ManageBanksAccountJPanel(JPanel upc, EcoSystem system, Bank bank, ManageBankDirectoryJPanel sa) {
        initComponents();
        this.upc = upc;
        this.system = system;
        this.sa = sa;
        this.bank = bank;
        populateTable();
        populateBnkComboBx();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateBnkComboBx() {
        bnkJCmbBx.removeAllItems();

        bnkJCmbBx.addItem(bank);

    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) usrAcctJTbl.getModel();
        dtm.setRowCount(0);

        // Bank b = (Bank) bnkJCmbBx.getSelectedItem();
        for (Bank bank : system.getBankDirectory().getBankList()) {
            for (UserAccount ua : bank.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = bank;
                dtm.addRow(row);
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usrAcctJTbl = new javax.swing.JTable();
        bnkJCmbBx = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        usrNmJTxtField = new javax.swing.JTextField();
        passwordJTxtField = new javax.swing.JTextField();
        nmJTxtField = new javax.swing.JTextField();
        createJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setText("Name");

        setBackground(new java.awt.Color(255, 255, 255));

        usrAcctJTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Bank Name"
            }
        ));
        jScrollPane1.setViewportView(usrAcctJTbl);

        bnkJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bnkJCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnkJCmbBxActionPerformed(evt);
            }
        });

        jLabel3.setText("Banks");

        usrNmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrNmJTxtFieldActionPerformed(evt);
            }
        });

        nmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmJTxtFieldActionPerformed(evt);
            }
        });

        createJBtn.setText("Create");
        createJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel1.setText("UserName");

        jLabel4.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createJBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bnkJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnkJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addComponent(createJBtn)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bnkJCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkJCmbBxActionPerformed
        // TODO add your handling code here:
        // populateBnkComboBx();
    }//GEN-LAST:event_bnkJCmbBxActionPerformed

    private void usrNmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrNmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrNmJTxtFieldActionPerformed

    private void nmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmJTxtFieldActionPerformed

    private void createJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJBtnActionPerformed
        // TODO add your handling code here:

        if (usrNmJTxtField.getText().trim().length() > 0 && passwordJTxtField.getText().trim().length() > 0
                && nmJTxtField.getText().trim().length() > 0) {

            String userName = usrNmJTxtField.getText().trim();
            Enterprise inEnterprise = null;
            Organization inOrganization = null;
            UserAccount userAccount = system.getUserAccountDirectory().searchUser(userName);
            if (userAccount == null) {
                    for (Network n : system.getNetworkList()) {
                        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                            userAccount = e.getUserAccountDirectory().searchUser(userName);
                            if (userAccount == null) {
                                for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                                    userAccount = o.getUserAccountDirectory().searchUser(userName);
                                    if (userAccount != null) {
                                        inOrganization = o;
                                        inEnterprise = e;

                                        break;
                                    }

                                }
                            } else {
                                inEnterprise = e;
                                break;
                            }
                            if (inOrganization != null) {
                                break;
                            }
                        }
                        if (inEnterprise != null) {
                            break;
                        }
                    }

                }

            if (userAccount == null) {
                for (Bank b : system.getBankDirectory().getBankList()) {
                    userAccount = b.getUserAccountDirectory().searchUser(userName);
                    if (userAccount == null) {
                        for (Organization o : b.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().searchUser(userName);
                            if (userAccount != null) {
                                break;
                            }
                        }
                    } else {
                        break;
                    }
                }
            }

            if (userAccount == null) {
                for (AdExchange ae : system.getAdExDir().getAdExchangeList()) {
                    userAccount = ae.getUserAccountDirectory().searchUser(userName);
                    if (userAccount == null) {
                        for (Organization o : ae.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().searchUser(userName);
                            if (userAccount != null) {
                                break;
                            }
                        }
                    } else {
                        break;
                    }
                }
            }
            if (userAccount == null) {
                Bank b = (Bank) bnkJCmbBx.getSelectedItem();
                Person p = b.getPersonDirectory().createPerson(nmJTxtField.getText().trim());
                b.getUserAccountDirectory().createUserAccount(userName, passwordJTxtField.getText().trim(), p, new BankAdminRole());
                populateTable();
                JOptionPane.showMessageDialog(null, "User Account Successfully Created");
                upc.remove(this);
                CardLayout layout = (CardLayout) upc.getLayout();
                layout.previous(upc);
            } else {
                JOptionPane.showMessageDialog(null, "Username already exists. Please use different Username");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Enter Values for Username or Password or Name");
        }
    }//GEN-LAST:event_createJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bnkJCmbBx;
    private javax.swing.JButton createJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmJTxtField;
    private javax.swing.JTextField passwordJTxtField;
    private javax.swing.JTable usrAcctJTbl;
    private javax.swing.JTextField usrNmJTxtField;
    // End of variables declaration//GEN-END:variables
}
