/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author AnanthaShankar
 */
public class SysAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminWorkAreaJPanel
     */
    private JPanel upc;
    private EcoSystem system;
    public SysAdminWorkAreaJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.upc = upc;
        this.system = system;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        netJTree = new javax.swing.JTree();
        manageNetworksJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageuserJButton = new javax.swing.JButton();
        rfrshJTreeBtn = new javax.swing.JButton();
        manageAdExJButton = new javax.swing.JButton();
        manageNetworksJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("System Admin Work Area");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        netJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        netJTree.setToolTipText("");
        netJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                netJTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(netJTree);

        manageNetworksJButton.setText("Manage Networks");
        manageNetworksJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworksJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        manageuserJButton.setText("Manage Enterprise Account");
        manageuserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageuserJButtonActionPerformed(evt);
            }
        });

        rfrshJTreeBtn.setText("Refresh Tree");
        rfrshJTreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfrshJTreeBtnActionPerformed(evt);
            }
        });

        manageAdExJButton.setText("Manage AdExchange");
        manageAdExJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdExJButtonActionPerformed(evt);
            }
        });

        manageNetworksJButton1.setText("Manage BankDirectory");
        manageNetworksJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworksJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rfrshJTreeBtn)
                    .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageNetworksJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(manageAdExJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageNetworksJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageuserJButton))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(manageNetworksJButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageNetworksJButton1)
                        .addGap(18, 18, 18)
                        .addComponent(manageAdExJButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageEnterpriseJButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageuserJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rfrshJTreeBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void populateNetworkTree(){
        
        DefaultTreeModel dtm = (DefaultTreeModel) netJTree.getModel();
        
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        ArrayList<Network> networkList = system.getNetworkList();
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) dtm.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        //populating networks
        for(int i=0; i < networkList.size(); i++){
            network = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
            //populating enterprises
            for(int k=0; k < enterpriseList.size(); k++){
                enterprise = enterpriseList.get(k);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, k);
                organizationList = enterprise.getOrganizationDirectory().getOrgList();
                //populating organizations
                for(int j=0; j < organizationList.size(); j++){
                    organization = organizationList.get(j);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    organization = organizationList.get(j);
                }
            }
        }
        dtm.reload();
        
    }
    
    private void netJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_netJTreeValueChanged
        // TODO add your handling code here:
        

    }//GEN-LAST:event_netJTreeValueChanged

    private void manageNetworksJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworksJButtonActionPerformed

        ManageNetworkJPanel mnp = new ManageNetworkJPanel(upc, system, this);
        upc.add("Manage Network", mnp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageNetworksJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed

        ManageEnterpriseJPanel mnp = new ManageEnterpriseJPanel(upc, system, this);
        upc.add("Manage Enterprise", mnp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageuserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageuserJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseUserAccountJPanel muajp = new ManageEnterpriseUserAccountJPanel(upc, system,this);
        upc.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageuserJButtonActionPerformed

    private void rfrshJTreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfrshJTreeBtnActionPerformed
        // TODO add your handling code here:
        populateNetworkTree();
    }//GEN-LAST:event_rfrshJTreeBtnActionPerformed

    private void manageAdExJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdExJButtonActionPerformed
        // TODO add your handling code here:
        ManageAdExChangeJPanel mnp = new ManageAdExChangeJPanel(upc, system, this);
        upc.add("Manage AdEx", mnp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
        
    }//GEN-LAST:event_manageAdExJButtonActionPerformed

    private void manageNetworksJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworksJButton1ActionPerformed
        // TODO add your handling code here:
        ManageBankDirectoryJPanel mnp = new ManageBankDirectoryJPanel(upc, system, this);
        upc.add("Manage bankDir", mnp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageNetworksJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageAdExJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworksJButton;
    private javax.swing.JButton manageNetworksJButton1;
    private javax.swing.JButton manageuserJButton;
    private javax.swing.JTree netJTree;
    private javax.swing.JButton rfrshJTreeBtn;
    // End of variables declaration//GEN-END:variables
}
