/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AdExchange;
import Business.Bank;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.UserRole.RegisterUserJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author AnanthaShankar
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem business;
    private DB4OUtil db4oUtil;

    public MainJFrame() {
        initComponents();
        db4oUtil = DB4OUtil.getInstance();
        business = db4oUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        usrNmJTxtField = new javax.swing.JTextField();
        passwordJTxtField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logInJBtn = new javax.swing.JButton();
        logOutJBtn = new javax.swing.JButton();
        registerJBtn = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftJPanel.setPreferredSize(new java.awt.Dimension(150, 298));

        passwordJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("UserName");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Password");

        logInJBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logInJBtn.setText("LogIn");
        logInJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInJBtnActionPerformed(evt);
            }
        });

        logOutJBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logOutJBtn.setText("LogOut");
        logOutJBtn.setEnabled(false);
        logOutJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutJBtnActionPerformed(evt);
            }
        });

        registerJBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registerJBtn.setText("Register User");
        registerJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrNmJTxtField)
                    .addComponent(passwordJTxtField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leftJPanelLayout.createSequentialGroup()
                        .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logInJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOutJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logInJBtn)
                .addGap(18, 18, 18)
                .addComponent(logOutJBtn)
                .addGap(18, 18, 18)
                .addComponent(registerJBtn)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJTxtFieldActionPerformed

    private void logOutJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutJBtnActionPerformed
        // TODO add your handling code here:
        db4oUtil.storeSystem(business);
        userProcessContainer.removeAll();
        dummyJPanel djp = new dummyJPanel();
        userProcessContainer.add("DummyPanel", djp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        JOptionPane.showMessageDialog(null, "Successfully Logged Out");
        usrNmJTxtField.setEnabled(true);
        passwordJTxtField.setEnabled(true);
        logInJBtn.setEnabled(true);
        registerJBtn.setEnabled(true);
        logOutJBtn.setEnabled(false);
    }//GEN-LAST:event_logOutJBtnActionPerformed

    private void registerJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJBtnActionPerformed
        // TODO add your handling code here:
        RegisterUserJPanel ruj = new RegisterUserJPanel(userProcessContainer, business);
        userProcessContainer.add("Register User" ,ruj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerJBtnActionPerformed

    private void logInJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInJBtnActionPerformed
        // TODO add your handling code here:
        String userName = usrNmJTxtField.getText();
        // Get Password
        char[] passwordCharArray = passwordJTxtField.getPassword();
        String password = String.valueOf(passwordCharArray);

        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        AdExchange inAdExchange = null;
        Bank inBank = null;

        UserAccount userAccount = business.getUserAccountDirectory().authenticateUser(userName, password);
        if (userAccount == null) {
            for (Network n : business.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = e.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                inOrganization = o;
                                inEnterprise = e;

                                break;
                            }
                        }
                    } else {
                        inEnterprise = e;
                        break;
                    }
                    if (inOrganization != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }

        }

        if (userAccount == null) {
            for (Bank b : business.getBankDirectory().getBankList()) {
                userAccount = b.getUserAccountDirectory().authenticateUser(userName, password);
                if (userAccount == null) {
                    for (Organization o : b.getOrganizationDirectory().getOrgList()) {
                        userAccount = o.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount != null) {
                            inBank = b;
                            break;
                        }
                    }
                } else {
                    inBank = b;
                    break;
                }
            } 
        }

            if (userAccount == null) {
                for (AdExchange ae : business.getAdExDir().getAdExchangeList()) {
                    userAccount = ae.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        for (Organization o : ae.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                inAdExchange = ae;
                                break;
                            }
                        }
                    } else {
                        inAdExchange = ae;
                        break;
                    }
                } 
            }

        //  /*for (Organization organization : business.getOrganizationDirectory().getOrganizationList()){
                //    userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                if (userAccount != null) {
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, business, inAdExchange, inBank));
                    layout.next(userProcessContainer);
                    usrNmJTxtField.setText(null);
                    passwordJTxtField.setText(null);
                    usrNmJTxtField.setEnabled(false);
                    passwordJTxtField.setEnabled(false);
                    logInJBtn.setEnabled(false);
                    registerJBtn.setEnabled(false);
                    logOutJBtn.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Credentials");
                }


    }//GEN-LAST:event_logInJBtnActionPerformed

    /**
             * @param args the command line arguments
             */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton logInJBtn;
    private javax.swing.JButton logOutJBtn;
    private javax.swing.JPasswordField passwordJTxtField;
    private javax.swing.JButton registerJBtn;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JTextField usrNmJTxtField;
    // End of variables declaration//GEN-END:variables
}
