/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserRole;

import Business.Advertisement;
import Business.CustomerHistory.CustomerBrowsing;
import Business.CustomerHistory.CustomerBrowsingHistory;
import Business.EcoSystem;
import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Person.Customer;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class DisplayPublisherProductAndAdJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPublisherProductAndAdJPanel
     */
    private JPanel upc;
    private EcoSystem system;
    private UserAccount ua;  
    private PublisherEnterprise e;
    private AdvertiserEnterprise ae;
    private Advertisement a; 
    private Product p;
    private Customer c;
    private String path = "download.jpg"; //remove this later
    public DisplayPublisherProductAndAdJPanel(JPanel upc, EcoSystem system, UserAccount ua,  
             PublisherEnterprise e, AdvertiserEnterprise ae, Advertisement a , Product p) {
        initComponents();
        this.upc = upc;
        this.ae = ae;
        this.ua = ua;
        this.system = system;
        this.e = e;
        this.p = p;
        this.a = a;
        if(a != null){
        this.path = a.getPath();}
        c = (Customer) ua.getPerson();
        CustomerBrowsing cb = c.getCustomerBrowsingHistory().addPublisherBrowsingHistory();
        cb.setInterest(p.getProductType());
        cb.setProduct(p.getProdName());
        cb.setPublisher(e.getName());
        productContentJTxtArea.setText(p.getProduct_Content());
        
        adSpace1.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productContentJTxtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        backJBtn = new javax.swing.JButton();
        adSpace = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        browsAdJBtn = new javax.swing.JButton();
        adSpace1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        productContentJTxtArea.setColumns(20);
        productContentJTxtArea.setRows(5);
        jScrollPane1.setViewportView(productContentJTxtArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Content");

        backJBtn.setText("<<  Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Advertisement Content");

        browsAdJBtn.setText("Browse Ad product");
        browsAdJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsAdJBtnActionPerformed(evt);
            }
        });

        adSpace1.setText("adSpace");
        adSpace1.setMinimumSize(new java.awt.Dimension(14, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(backJBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(adSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adSpace))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(browsAdJBtn)
                            .addComponent(jLabel3))
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(63, 63, 63)
                        .addComponent(adSpace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adSpace)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browsAdJBtn)
                    .addComponent(backJBtn))
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void browsAdJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsAdJBtnActionPerformed
        // TODO add your handling code here:
        //afterclicking ad update cust click history, anb advertiser browsing history in customer browsing history also update advertiser, publisher purchase history in previous
        //window for ad purchase
        if(a != null){
        int i = c.getNoOfClicksCount();
        c.setNoOfClicksCount(i + 1);
        CustomerBrowsing cb = c.getCustomerBrowsingHistory().addAdvertiserBrowsingHistory();
        cb.setInterest(p.getProductType());
        cb.setPublisher(ae.getName());
        cb.setProduct("Ad View");
        AdvertiserProductDisplayJPanel utj = new AdvertiserProductDisplayJPanel(upc, ae, system, a.getInterest(), 
        ua, e);
            upc.add("User Transaction",utj);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        }
        else {
            JOptionPane.showMessageDialog(null, "No Advertiser To Display");
        }
        
    }//GEN-LAST:event_browsAdJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adSpace;
    private javax.swing.JLabel adSpace1;
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton browsAdJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea productContentJTxtArea;
    // End of variables declaration//GEN-END:variables
}
