/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserRole;

import Business.AdExchange;
import Business.Bank;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.UserOrganization;
import Business.Person.Customer;
import Business.Person.Person;
import Business.Role.Role;
import Business.Role.UserRole;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class RegisterUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterUserJPanel
     */
    private JPanel upc;
    private EcoSystem system;

    public RegisterUserJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.upc = upc;
        this.system = system;
        pubJCmbBx.removeAllItems();
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof PublisherEnterprise) {
                    pubJCmbBx.addItem(e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pubJCmbBx = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nmJTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ageJTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        locJTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        acctHldrNmJTxtField = new javax.swing.JTextField();
        bnkNmJTxtField = new javax.swing.JTextField();
        uniqIdJTxtField = new javax.swing.JTextField();
        acctTypJTxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usrNmJTxtField = new javax.swing.JTextField();
        passJTxtField = new javax.swing.JTextField();
        crtUsrAcctJBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select a Publisher to Register");

        pubJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pubJCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubJCmbBxActionPerformed(evt);
            }
        });

        jLabel2.setText("Publishers");

        jLabel3.setText("Name");

        jLabel4.setText("Age");

        jLabel5.setText("Location");

        jLabel6.setText("AccountHolder Name");

        jLabel7.setText("Bank Name");

        jLabel8.setText("Account Type");

        jLabel9.setText("Unique Id");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Finance Account Details (Optional)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Personal Details");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("User Account Details");

        jLabel13.setText("UserName");

        jLabel14.setText("Password");

        crtUsrAcctJBtn.setText("Create User Account");
        crtUsrAcctJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtUsrAcctJBtnActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Note : Finance Account is\nonly used for verification\npurpose and is optional to \nenter. To process a transac\ntion you might need more \nthan the details provided \nhere");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acctTypJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uniqIdJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acctHldrNmJTxtField)
                                    .addComponent(bnkNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pubJCmbBx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nmJTxtField)
                                    .addComponent(ageJTxtField)
                                    .addComponent(locJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crtUsrAcctJBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(passJTxtField)
                                .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ageJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(locJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(acctHldrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bnkNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uniqIdJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acctTypJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(usrNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(passJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(crtUsrAcctJBtn)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pubJCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubJCmbBxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pubJCmbBxActionPerformed

    private void crtUsrAcctJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtUsrAcctJBtnActionPerformed
        // TODO add your handling code here:
        try{
        if (nmJTxtField.getText().trim().length() > 0 && ageJTxtField.getText().trim().length() > 0
                && locJTxtField.getText().trim().length() > 0 && usrNmJTxtField.getText().trim().length() > 0
                && passJTxtField.getText().trim().length() > 0) {
            String userName = usrNmJTxtField.getText().trim();
            String password = passJTxtField.getText().trim();

            UserAccount userAccount = system.getUserAccountDirectory().searchUser(userName);
            if (userAccount == null) {
                for (Network n : system.getNetworkList()) {
                    for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                        userAccount = e.getUserAccountDirectory().searchUser(userName);
                        if (userAccount == null) {
                            for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                                userAccount = o.getUserAccountDirectory().searchUser(userName);

                            }
                        } else {
                            break;
                        }

                    }

                }

            }

            if (userAccount == null) {
            for (Bank b : system.getBankDirectory().getBankList()) {
                userAccount = b.getUserAccountDirectory().searchUser(userName);
                if (userAccount == null) {
                    for (Organization o : b.getOrganizationDirectory().getOrgList()) {
                        userAccount = o.getUserAccountDirectory().searchUser(userName);
                        if (userAccount != null) {
                            break;
                        }
                    }
                } else {
                    break;
                }
            } 
        }

            if (userAccount == null) {
                for (AdExchange ae : system.getAdExDir().getAdExchangeList()) {
                    userAccount = ae.getUserAccountDirectory().searchUser(userName);
                    if (userAccount == null) {
                        for (Organization o : ae.getOrganizationDirectory().getOrgList()) {
                            userAccount = o.getUserAccountDirectory().searchUser(userName);
                            if (userAccount != null) {
                                break;
                            }
                        }
                    } else {
                        break;
                    }
                } 
            }
            
            if (userAccount == null) {
                PublisherEnterprise e = (PublisherEnterprise) pubJCmbBx.getSelectedItem();
                for (Organization o : e.getOrganizationDirectory().getOrgList()) {
                    if (o instanceof UserOrganization) {
                        //  Organization organization = (Organization) organizationJComboBox.getSelectedItem();
                        //  Person p = (Person) employeeJComboBox.getSelectedItem();
                        Customer c = new Customer();
                        c.setName(nmJTxtField.getText().trim());
                        
                        c.setAge(Integer.parseInt(ageJTxtField.getText().trim()));
                        c.setLocation(locJTxtField.getText().trim());
                        if (acctHldrNmJTxtField.getText().trim().length() > 0
                                && bnkNmJTxtField.getText().trim().length() > 0
                                && acctTypJTxtField.getText().trim().length() > 0
                                && uniqIdJTxtField.getText().trim().length() > 0) {

                            c.getAccount().setAccountHolderName(acctHldrNmJTxtField.getText().trim());
                            c.getAccount().setAccountType(acctTypJTxtField.getText().trim());
                            c.getAccount().setBankName(bnkNmJTxtField.getText().trim());
                            c.getAccount().setUniqueId(uniqIdJTxtField.getText().trim());
                        }
                        e.getPersonDirectory().getPersonList().add(c);
                        o.getUserAccountDirectory().createUserAccount(userName, password, c, new UserRole());
                        JOptionPane.showMessageDialog(null, "User Account Successfully Created");
                        break;
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Username already exists. Please use different Username");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Invalid Personal or User Account Inputs");
        }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error Age Value");
        }
    }//GEN-LAST:event_crtUsrAcctJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctHldrNmJTxtField;
    private javax.swing.JTextField acctTypJTxtField;
    private javax.swing.JTextField ageJTxtField;
    private javax.swing.JTextField bnkNmJTxtField;
    private javax.swing.JButton crtUsrAcctJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField locJTxtField;
    private javax.swing.JTextField nmJTxtField;
    private javax.swing.JTextField passJTxtField;
    private javax.swing.JComboBox pubJCmbBx;
    private javax.swing.JTextField uniqIdJTxtField;
    private javax.swing.JTextField usrNmJTxtField;
    // End of variables declaration//GEN-END:variables
}
