/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Person.Customer;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class UserWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserWorkAreaJPanel
     */
    private JPanel upc;
    private PublisherEnterprise e;
    private EcoSystem system;
    private UserAccount ua;

    public UserWorkAreaJPanel(JPanel upc, Enterprise e, EcoSystem system, UserAccount ua) {
        initComponents();
        this.upc = upc;
        this.e = (PublisherEnterprise) e;
        this.system = system;
        this.ua = ua;
        welcmJLabel.setText("Welcome To " + e.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcmJLabel = new javax.swing.JLabel();
        clothJBtn = new javax.swing.JButton();
        educationJBtn = new javax.swing.JButton();
        electronicJBtn = new javax.swing.JButton();
        foodJBtn = new javax.swing.JButton();
        musicJBtn = new javax.swing.JButton();
        moviesJBtn = new javax.swing.JButton();
        sportsJBtn = new javax.swing.JButton();
        travelJBtn = new javax.swing.JButton();
        vehicleJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        welcmJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        clothJBtn.setBackground(new java.awt.Color(204, 204, 255));
        clothJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clothJBtn.setText("Clothes");
        clothJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothJBtnActionPerformed(evt);
            }
        });

        educationJBtn.setBackground(new java.awt.Color(204, 204, 255));
        educationJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        educationJBtn.setText("Education");
        educationJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationJBtnActionPerformed(evt);
            }
        });

        electronicJBtn.setBackground(new java.awt.Color(204, 204, 255));
        electronicJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        electronicJBtn.setText("Electronics");
        electronicJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronicJBtnActionPerformed(evt);
            }
        });

        foodJBtn.setBackground(new java.awt.Color(204, 204, 255));
        foodJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        foodJBtn.setText("Food");
        foodJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodJBtnActionPerformed(evt);
            }
        });

        musicJBtn.setBackground(new java.awt.Color(204, 204, 255));
        musicJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        musicJBtn.setText("Music");
        musicJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicJBtnActionPerformed(evt);
            }
        });

        moviesJBtn.setBackground(new java.awt.Color(204, 204, 255));
        moviesJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        moviesJBtn.setText("Movies");
        moviesJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviesJBtnActionPerformed(evt);
            }
        });

        sportsJBtn.setBackground(new java.awt.Color(204, 204, 255));
        sportsJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sportsJBtn.setText("Sports");
        sportsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsJBtnActionPerformed(evt);
            }
        });

        travelJBtn.setBackground(new java.awt.Color(204, 204, 255));
        travelJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        travelJBtn.setText("Travel");
        travelJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelJBtnActionPerformed(evt);
            }
        });

        vehicleJBtn.setBackground(new java.awt.Color(204, 204, 255));
        vehicleJBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vehicleJBtn.setText("Vehicle");
        vehicleJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clothJBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(foodJBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sportsJBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(travelJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moviesJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electronicJBtn)
                            .addComponent(vehicleJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(welcmJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcmJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electronicJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(educationJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moviesJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportsJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(travelJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void educationJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationJBtnActionPerformed
        // TODO add your handling code here:

        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Education")) {

        } else {
            c.getInterests().add("Education");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Education")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Education");
            upc.add("Edcucation Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_educationJBtnActionPerformed

    private void foodJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Food")) {

        } else {
            c.getInterests().add("Food");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Food")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Food");
            upc.add("Food Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_foodJBtnActionPerformed

    private void clothJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Clothes")) {

        } else {
            c.getInterests().add("Clothes");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Clothes")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Clothes");
            upc.add("Clothes Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_clothJBtnActionPerformed

    private void electronicJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronicJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Electronics")) {

        } else {
            c.getInterests().add("Electronics");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Electronics")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Electronics");
            upc.add("Electronics Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_electronicJBtnActionPerformed

    private void musicJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Music")) {

        } else {
            c.getInterests().add("Music");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Music")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Music");
            upc.add("Music Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_musicJBtnActionPerformed

    private void moviesJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviesJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Movies")) {

        } else {
            c.getInterests().add("Movies");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Movies")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Movies");
            upc.add("Movies Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_moviesJBtnActionPerformed

    private void sportsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Sports")) {

        } else {
            c.getInterests().add("Sports");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Sports")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Sports");
            upc.add("Sports Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_sportsJBtnActionPerformed

    private void travelJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Travel")) {

        } else {
            c.getInterests().add("Travel");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Travel")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Travel");
            upc.add("Travel Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_travelJBtnActionPerformed

    private void vehicleJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleJBtnActionPerformed
        // TODO add your handling code here:
        Customer c = (Customer) ua.getPerson();
        if (c.getInterests().contains("Vehicle")) {

        } else {
            c.getInterests().add("Vehicle");
        }
        int i = 0;
        for (Product p : e.getProdDir().getProductCatalog()) {
            if (p.getProductType().equalsIgnoreCase("Vehicle")) {
                i = 1;
                break;
            }
        }
        if (i == 1) {
            PublisherProductDisplayJpanel ppd = new PublisherProductDisplayJpanel(upc, system, ua, e, "Vehicle");
            upc.add("Vehicle Products", ppd);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else {
            JOptionPane.showMessageDialog(null, "No Products To Display In This Category");
        }
    }//GEN-LAST:event_vehicleJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clothJBtn;
    private javax.swing.JButton educationJBtn;
    private javax.swing.JButton electronicJBtn;
    private javax.swing.JButton foodJBtn;
    private javax.swing.JButton moviesJBtn;
    private javax.swing.JButton musicJBtn;
    private javax.swing.JButton sportsJBtn;
    private javax.swing.JButton travelJBtn;
    private javax.swing.JButton vehicleJBtn;
    private javax.swing.JLabel welcmJLabel;
    // End of variables declaration//GEN-END:variables
}
