/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagerRole;

import Business.Product.Product;
import Business.Product.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class CreateProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateProductJPanel
     */
    private JPanel upc;
    private ProductDirectory directory;
    private String category;
    public CreateProductJPanel(JPanel upc, ProductDirectory directory, String category) {
        initComponents();
        this.upc = upc;
        this.directory = directory;
        this.category = category;
        prodCatgJTxtField.setText(category);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prodCatgJTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prodNmJTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        crtProdJBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodContentJTxtArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        bckJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create Product");

        prodCatgJTxtField.setEditable(false);

        jLabel2.setText("Product Category");

        prodNmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodNmJTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Name");

        crtProdJBtn.setText("Create Product");
        crtProdJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtProdJBtnActionPerformed(evt);
            }
        });

        prodContentJTxtArea.setColumns(20);
        prodContentJTxtArea.setRows(5);
        jScrollPane1.setViewportView(prodContentJTxtArea);

        jLabel4.setText("Product Content");

        bckJBtn.setText("<<  Back");
        bckJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(bckJBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(crtProdJBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addComponent(prodNmJTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(prodCatgJTxtField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodCatgJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtProdJBtn)
                    .addComponent(bckJBtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prodNmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodNmJTxtFieldActionPerformed

    private void crtProdJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtProdJBtnActionPerformed
        // TODO add your handling code here:
    if(prodNmJTxtField.getText().trim().length() > 0 && prodCatgJTxtField.getText().trim().length() > 0 &&
            prodContentJTxtArea.getText().trim().length() > 0){
        Product p =  directory.addProduct();
        p.setProdName( prodNmJTxtField.getText().trim());
        p.setProduct_Content(prodContentJTxtArea.getText());
        p.setProductType(prodCatgJTxtField.getText());
        int count = directory.getProductCatalog().size(); 
        p.setProductId((directory.getProductCatalog().get( count - 1).getProductId()) + 1);
        JOptionPane.showMessageDialog(null, "Product Created Successfully");
    } else {
        JOptionPane.showMessageDialog(null, "Invalid Product Creation");
    }
        
        
    }//GEN-LAST:event_crtProdJBtnActionPerformed

    private void bckJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckJBtnActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_bckJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckJBtn;
    private javax.swing.JButton crtProdJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prodCatgJTxtField;
    private javax.swing.JTextArea prodContentJTxtArea;
    private javax.swing.JTextField prodNmJTxtField;
    // End of variables declaration//GEN-END:variables
}
