/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProductManagerRole;

import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Product.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class ProductManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductManagerWorkAreaJPanel
     */
    private JPanel upc;
    private Enterprise enterprise;

    public ProductManagerWorkAreaJPanel(JPanel upc, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        catgJCmbBx.removeAllItems();
        catgJCmbBx.addItem("Clothes");
        catgJCmbBx.addItem("Education");
        catgJCmbBx.addItem("Electronics");
        catgJCmbBx.addItem("Food");
        catgJCmbBx.addItem("Music");
        catgJCmbBx.addItem("Movies");
        catgJCmbBx.addItem("Sports");
        catgJCmbBx.addItem("Travel");
        catgJCmbBx.addItem("Vehicles");
        if (enterprise.getType().getValue().equals(Enterprise.EnterpriseType.Advertiser.getValue())){
            createAdJBtn.setEnabled(true);
        }

        // should be given a option to add web page and create links under different category
        // Sports, Educational, Travel, Vehicles, Music, Electronics, Clothes, Food, 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crtProdJBtn = new javax.swing.JButton();
        catgJCmbBx = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createAdJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        crtProdJBtn.setText("Create Product");
        crtProdJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtProdJBtnActionPerformed(evt);
            }
        });

        catgJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Product Category");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Product Manager Work Area");

        createAdJBtn.setText("Create Ad");
        createAdJBtn.setEnabled(false);
        createAdJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createAdJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(crtProdJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(catgJCmbBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catgJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(46, 46, 46)
                .addComponent(crtProdJBtn)
                .addGap(29, 29, 29)
                .addComponent(createAdJBtn)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crtProdJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtProdJBtnActionPerformed
        // TODO add your handling code here:
        if (enterprise.getType().getValue().equals(Enterprise.EnterpriseType.Publisher.getValue())) {
            PublisherEnterprise e = (PublisherEnterprise) enterprise;
            ProductDirectory directory = e.getProdDir();
            CreateProductJPanel cjp = new CreateProductJPanel(upc, directory, (String) catgJCmbBx.getSelectedItem());
            upc.add("Create Product", cjp);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        } else if (enterprise.getType().getValue().equals(Enterprise.EnterpriseType.Advertiser.getValue())) {
                    AdvertiserEnterprise e = (AdvertiserEnterprise) enterprise;
                    CreateAdvertiserProductJPanel cjp = new CreateAdvertiserProductJPanel(upc, e, (String) catgJCmbBx.getSelectedItem(), 0);
                    upc.add("Create Ad Product", cjp);
                    CardLayout layout = (CardLayout) upc.getLayout();
                    layout.next(upc);
        }


    }//GEN-LAST:event_crtProdJBtnActionPerformed

    private void createAdJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdJBtnActionPerformed
        // TODO add your handling code here:
                    AdvertiserEnterprise e = (AdvertiserEnterprise) enterprise;
                    CreateAdvertiserProductJPanel cjp = new CreateAdvertiserProductJPanel(upc, e, (String) catgJCmbBx.getSelectedItem(), 1);
                    upc.add("Create Ad Product", cjp);
                    CardLayout layout = (CardLayout) upc.getLayout();
                    layout.next(upc);
    }//GEN-LAST:event_createAdJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox catgJCmbBx;
    private javax.swing.JButton createAdJBtn;
    private javax.swing.JButton crtProdJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
