/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankAccountManager;

import Business.Bank;
import Business.BankAccount;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class BankAccountManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankAccountManagerWorkAreaJPanel
     */
    private JPanel upc;
    private Bank b;

    public BankAccountManagerWorkAreaJPanel(JPanel upc, Bank b) {
        initComponents();
        this.upc = upc;
        this.b = b;
        acctTypJCmbBx.removeAllItems();
        acctTypJCmbBx.addItem("Consumer");
        acctTypJCmbBx.addItem("Retail");
        cardTypJCmbBx.removeAllItems();
        cardTypJCmbBx.addItem("Mastercard");
        cardTypJCmbBx.addItem("Visa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nmJTxtField3 = new javax.swing.JLabel();
        nmJTxtField = new javax.swing.JTextField();
        addrJTxtField = new javax.swing.JTextField();
        balAmtJTxtField = new javax.swing.JTextField();
        crtAcctJBtn = new javax.swing.JButton();
        cardTypJCmbBx = new javax.swing.JComboBox();
        acctTypJCmbBx = new javax.swing.JComboBox();
        cardPinJTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        viewJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Account Holder Name");

        jLabel2.setText("Card Type");

        jLabel3.setText("Account Type");

        jLabel4.setText("Address");

        jLabel5.setText("BalanceAmount");

        nmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmJTxtFieldActionPerformed(evt);
            }
        });

        addrJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrJTxtFieldActionPerformed(evt);
            }
        });

        balAmtJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balAmtJTxtFieldActionPerformed(evt);
            }
        });

        crtAcctJBtn.setText("Create Account");
        crtAcctJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtAcctJBtnActionPerformed(evt);
            }
        });

        cardTypJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        acctTypJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cardPinJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPinJTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Card Pin");

        viewJBtn.setText("View Accounts");
        viewJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(47, 47, 47))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardPinJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardTypJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nmJTxtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balAmtJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acctTypJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewJBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crtAcctJBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(acctTypJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addrJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(balAmtJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nmJTxtField3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardTypJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardPinJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(crtAcctJBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewJBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmJTxtFieldActionPerformed

    private void addrJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrJTxtFieldActionPerformed

    private void balAmtJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balAmtJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balAmtJTxtFieldActionPerformed

    private void crtAcctJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtAcctJBtnActionPerformed
        // TODO add your handling code here:
        try {
            if (nmJTxtField.getText().trim().length() > 0 && addrJTxtField.getText().trim().length() > 0
                    && balAmtJTxtField.getText().trim().length() > 0
                    && cardPinJTxtField.getText().trim().length() > 0) {
                String dt;
                Date date;
                SimpleDateFormat sf = new SimpleDateFormat("MM/yyyy");
                date = Calendar.getInstance().getTime();
                dt = sf.format(date);
                String acct_typ = (String) acctTypJCmbBx.getSelectedItem();
                String card_typ = (String) cardTypJCmbBx.getSelectedItem();
                String address = addrJTxtField.getText();
                float bal_amt = Float.parseFloat(balAmtJTxtField.getText());
                int count = b.getBankAccountList().size();
                int acct_num = 0;
                if(count > 0){
                BankAccount ba = b.getBankAccountList().get(count - 1);
                acct_num = ba.getAccountNumber() + 1;} 
                else {
                   acct_num =1;
                }
                String name = nmJTxtField.getText().trim();
                String unique_id = b.getName().substring(0, 2) + acct_typ.substring(0, 1) + "00"
                        + acct_typ.substring(acct_typ.length() - 3) + String.valueOf(acct_num);
                long card_num = (1111111111111111L + acct_num);
                String temp1 = dt.substring(0, 2);
                String temp2 = String.valueOf(Integer.valueOf(dt.substring(3)) + 10);
                String card_expiry = temp1 + "/" + temp2;
                BankAccount account = new BankAccount();
                account.setAccountHolderName(name);
                account.setAccountNumber(acct_num);
                account.setAccountType(acct_typ);
                account.setAddress(address);
                account.setBalanceAmount(bal_amt);
                account.setCardExpireDate(card_expiry);
                account.setCardPin(cardPinJTxtField.getText());
                account.setCardType(card_typ);
                account.setUniqueId(unique_id);
                account.setCardNumber(card_num);
                b.getBankAccountList().add(account);
                JOptionPane.showMessageDialog(null, "Acccount Added Successfully");

            } else {
                JOptionPane.showMessageDialog(null, "Invalid Inputs");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Input Value");
        }

    }//GEN-LAST:event_crtAcctJBtnActionPerformed

    private void cardPinJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPinJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardPinJTxtFieldActionPerformed

    private void viewJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJBtnActionPerformed
        // TODO add your handling code here:
        ViewAvailableAccountsJPanel vaa = new ViewAvailableAccountsJPanel(upc, b);
        upc.add("Available Acounts", vaa);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_viewJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox acctTypJCmbBx;
    private javax.swing.JTextField addrJTxtField;
    private javax.swing.JTextField balAmtJTxtField;
    private javax.swing.JTextField cardPinJTxtField;
    private javax.swing.JComboBox cardTypJCmbBx;
    private javax.swing.JButton crtAcctJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nmJTxtField;
    private javax.swing.JLabel nmJTxtField3;
    private javax.swing.JButton viewJBtn;
    // End of variables declaration//GEN-END:variables
}
