/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PlatformManagerRole;

import Business.AdExchange;
import Business.EcoSystem;
import Business.Enterprise.AdvertiserEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import Business.Network.Network;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class AdExPlatformManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdExPlatformManagerWorkAreaJPanel
     */
    private JPanel upc;
    private AdExchange adEx;
    private Enterprise enterprise;
    private EcoSystem system;

    public AdExPlatformManagerWorkAreaJPanel(JPanel upc, AdExchange adEx, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        this.system = system;
        this.adEx = adEx;
        populateCmbBx();
    }

    public void populateCmbBx() {
        adEntprJCmbBx.removeAllItems();
        pubEntrJCmbBx.removeAllItems();
        ArrayList<PublisherEnterprise> p = new ArrayList<PublisherEnterprise>();
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                int i = 0;
                if (e instanceof PublisherEnterprise) {
                    PublisherEnterprise pe = (PublisherEnterprise) e;
                    for (AdExchange ae : system.getAdExDir().getAdExchangeList()) {
                        if (ae.getPublisherList().contains(pe)) {
                            i = 1;
                            break;
                        }
                    }
                    if (i == 0) {
                        p.add(pe);
                    }
                }
            }
        }

        for (PublisherEnterprise pe : p) {
            pubEntrJCmbBx.addItem(pe);
        }
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof AdvertiserEnterprise) {
                    adEntprJCmbBx.addItem(e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAdvertJBtn = new javax.swing.JButton();
        addPublisherJBtn = new javax.swing.JButton();
        adEntprJCmbBx = new javax.swing.JComboBox();
        pubEntrJCmbBx = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        addAdvertJBtn.setText("Add Advertiser");
        addAdvertJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdvertJBtnActionPerformed(evt);
            }
        });

        addPublisherJBtn.setText("Add Publisher");
        addPublisherJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPublisherJBtnActionPerformed(evt);
            }
        });

        adEntprJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pubEntrJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Add Enterprises");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adEntprJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pubEntrJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addPublisherJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAdvertJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adEntprJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAdvertJBtn))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubEntrJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPublisherJBtn))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAdvertJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdvertJBtnActionPerformed
        // TODO add your handling code here:
        AdvertiserEnterprise ae = (AdvertiserEnterprise) adEntprJCmbBx.getSelectedItem();
        for(AdvertiserEnterprise ade : adEx.getAdvertiserList()){
        if(ade.getName().equals(ae.getName())){
            JOptionPane.showMessageDialog(null, "Advertiser Already A Member");
            break;
        } else {
           adEx.addAdvertiser(ae);
           JOptionPane.showMessageDialog(null, "Advertiser Succesfully Added"); 
        }
    }
        
        
    }//GEN-LAST:event_addAdvertJBtnActionPerformed

    private void addPublisherJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPublisherJBtnActionPerformed
        // TODO add your handling code here:
        PublisherEnterprise ae = (PublisherEnterprise) pubEntrJCmbBx.getSelectedItem();
        adEx.addPublisher(ae);
        JOptionPane.showMessageDialog(null, "Publisher Succesfully Added");
        populateCmbBx();
    }//GEN-LAST:event_addPublisherJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox adEntprJCmbBx;
    private javax.swing.JButton addAdvertJBtn;
    private javax.swing.JButton addPublisherJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox pubEntrJCmbBx;
    // End of variables declaration//GEN-END:variables
}
