/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PlatformManagerRole;

import Business.BiddingPlatform.SellSideBiddingPlatform;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PublisherEnterprise;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class PlatformManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlatformManagerWorkAreaJPanel
     */
    private JPanel upc;
    private PublisherEnterprise enterprise;
    private EcoSystem system;
    public PlatformManagerWorkAreaJPanel(JPanel upc, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.upc = upc;
        this.enterprise = (PublisherEnterprise) enterprise;
        this.system = system;
        usrAgeJCmbBx.removeAllItems();
        usrAgeJCmbBx.addItem("Teen"); // 10 - 20
        usrAgeJCmbBx.addItem("Young"); // 20 - 30
        usrAgeJCmbBx.addItem("Middle Aged"); // 30 - 50
        usrAgeJCmbBx.addItem("Aged"); // 50+
        
        
        // allowed to send request to register to ad exchange
        // allowed to create ssp and dsps respectively in structured manner
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usrAgeJCmbBx = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prodPurchJTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usrClickJTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prodBrowseJTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pubBrowseJTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        minBidJTxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        crtSspJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        usrAgeJCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sell Side Bidding Platform ");

        jLabel2.setText("UserAge");

        prodPurchJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodPurchJTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Purchase Product Count ");

        usrClickJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrClickJTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("User Click Count ");

        prodBrowseJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodBrowseJTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Product Browse Count ");

        pubBrowseJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pubBrowseJTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Publisher Browse Count ");

        minBidJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minBidJTxtFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Minimum Bidding Amount");

        crtSspJBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        crtSspJBtn.setText("Create SSP");
        crtSspJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtSspJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crtSspJBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prodPurchJTxtField)
                                .addComponent(usrAgeJCmbBx, 0, 90, Short.MAX_VALUE)
                                .addComponent(usrClickJTxtField)
                                .addComponent(prodBrowseJTxtField)
                                .addComponent(pubBrowseJTxtField)
                                .addComponent(minBidJTxtField)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrAgeJCmbBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodPurchJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrClickJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodBrowseJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubBrowseJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minBidJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(crtSspJBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prodPurchJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodPurchJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodPurchJTxtFieldActionPerformed

    private void usrClickJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrClickJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrClickJTxtFieldActionPerformed

    private void prodBrowseJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodBrowseJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodBrowseJTxtFieldActionPerformed

    private void pubBrowseJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pubBrowseJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pubBrowseJTxtFieldActionPerformed

    private void minBidJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minBidJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minBidJTxtFieldActionPerformed

    private void crtSspJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtSspJBtnActionPerformed
        // TODO add your handling code here:
        try{
        if(prodPurchJTxtField.getText().trim().length() > 0 && usrClickJTxtField.getText().trim().length() > 0 && 
                prodBrowseJTxtField.getText().trim().length() > 0 && pubBrowseJTxtField.getText().trim().length() > 0 && 
                minBidJTxtField.getText().trim().length() > 0){
                SellSideBiddingPlatform s = enterprise.addSsp();
                s.setMinBidValue(Float.parseFloat(minBidJTxtField.getText().trim()));
                s.setNoOfClicksCount(Integer.parseInt(pubBrowseJTxtField.getText().trim()));
                s.setUserClickCount(Integer.parseInt(usrClickJTxtField.getText().trim()));
                s.setProductBrowseCount(Integer.parseInt(prodBrowseJTxtField.getText().trim()));
                s.setNoOfPurchaseAdProductCount(Integer.parseInt(prodPurchJTxtField.getText().trim()));
                JOptionPane.showMessageDialog(null, "SSP creation successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Inputs Values");
        }
        } 
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid Input Value");
        }
    }//GEN-LAST:event_crtSspJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crtSspJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField minBidJTxtField;
    private javax.swing.JTextField prodBrowseJTxtField;
    private javax.swing.JTextField prodPurchJTxtField;
    private javax.swing.JTextField pubBrowseJTxtField;
    private javax.swing.JComboBox usrAgeJCmbBx;
    private javax.swing.JTextField usrClickJTxtField;
    // End of variables declaration//GEN-END:variables
}
