/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AnanthaShankar
 */
public class CreateFinanceAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFinanceAccountJPanel
     */
    private JPanel upc;
    private Enterprise business;
    public CreateFinanceAccountJPanel(JPanel upc, Enterprise business) {
        initComponents();
        this.upc = upc;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adBnkNmJTxtField = new javax.swing.JTextField();
        adAcctTypJTxtField = new javax.swing.JTextField();
        uniqueIdJTxtField = new javax.swing.JTextField();
        adAcctHldNmJTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crtFinanceAcctJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        adBnkNmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adBnkNmJTxtFieldActionPerformed(evt);
            }
        });

        adAcctTypJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adAcctTypJTxtFieldActionPerformed(evt);
            }
        });

        uniqueIdJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniqueIdJTxtFieldActionPerformed(evt);
            }
        });

        adAcctHldNmJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adAcctHldNmJTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Advertiser Bank Name");

        jLabel3.setText("Advertiser Account Holder Name");

        jLabel4.setText("Account Unique ID");

        jLabel5.setText("Advertiser Account Type");

        crtFinanceAcctJBtn.setText("Create Finance Account");
        crtFinanceAcctJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtFinanceAcctJBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Create Finance Account");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adAcctTypJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uniqueIdJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adBnkNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adAcctHldNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(38, 38, 38)
                        .addComponent(crtFinanceAcctJBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adBnkNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adAcctHldNmJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(uniqueIdJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adAcctTypJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtFinanceAcctJBtn)
                    .addComponent(backJButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adBnkNmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adBnkNmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adBnkNmJTxtFieldActionPerformed

    private void adAcctTypJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adAcctTypJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adAcctTypJTxtFieldActionPerformed

    private void uniqueIdJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniqueIdJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniqueIdJTxtFieldActionPerformed

    private void adAcctHldNmJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adAcctHldNmJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adAcctHldNmJTxtFieldActionPerformed

    private void crtFinanceAcctJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtFinanceAcctJBtnActionPerformed
        // TODO add your handling code here:
        if(adAcctHldNmJTxtField.getText().trim().length() > 0 && adAcctTypJTxtField.getText().trim().length() > 0 && 
                adBnkNmJTxtField.getText().trim().length() > 0 && uniqueIdJTxtField.getText().trim().length() > 0){
        business.getFa().setAccountHolderName(adAcctHldNmJTxtField.getText().trim());
        business.getFa().setAccountType(adAcctTypJTxtField.getText().trim());
        business.getFa().setBankName(adBnkNmJTxtField.getText().trim());
        business.getFa().setUniqueId(uniqueIdJTxtField.getText().trim());
        JOptionPane.showMessageDialog(null, "Account Added Successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Inputs");
        }
    }//GEN-LAST:event_crtFinanceAcctJBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adAcctHldNmJTxtField;
    private javax.swing.JTextField adAcctTypJTxtField;
    private javax.swing.JTextField adBnkNmJTxtField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton crtFinanceAcctJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField uniqueIdJTxtField;
    // End of variables declaration//GEN-END:variables
}
